name: "Deploy staging"

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: "Docker tag to deploy"
        required: true
        type: string
      ref:
        description: "Branch, tag, or SHA to checkout"
        required: false
        type: string
        default: "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Deploy using Tapit
        uses: tapitalee/ghactions/image-deploy@main
        with:
          tapit-token: ${{ secrets.TAPIT_TOKEN_STAGING }}
          docker_tag: ${{ inputs.docker_tag }}
